### ISSUE TITLE
No block source available

### ISSUE THREAD

**Issue by lexrms** [LUX-Core/lux#10]
Hello,

My wallet says "No block source available" and it is "8 days behind".

I am using version 5.2.2.0-a2083ff that I compiled myself on linux

What should I do?

Thank you

**Comment by tpruvot** [comment]
this branch/commit was not ready, please recompile

**Comment by lexrms** [comment]
@tpruvot 

Recompiled version: v5.2.3.0-b4aa45fxel

Same result, "No block source available" and it is "9 days behind"...
