### ISSUE TITLE
Lux-qt

### ISSUE THREAD

**Issue by aionmine-help** [LUX-Core/lux#14]
Problem with lux-qt
BTW: Awesome coin and glad Tanguy is now on the team!

tested in lux.conf
stake=0 and mint=0 does not stop the wallet from staking.

Further TX outputs listed in masternodes.conf are not kept from staking or blocked from spending with a Lock ICON.

When unlocking the wallet to send MN generated inputs during the transaction countdown (5 seconds) to press ok the 16120lux stakes almost instantly requiring an 80 block wait and regeneration of the masternode output.

The current workaround solution we are using is to sync the wallet, close the wallet.  Wait a few blocks and quickly make the transaction before the wallet is fully synced again so staking function can't enable.

I realize lux now has a stronger team and a real path forward and wanted to bring this SMALL issue forward that MN holders are experiencing.

Please advise if we have made a mistake somewhere.  Thank you!

**Comment by TopoX84** [comment]
Greetings,
there is no problem with Lux-QT
when sending coins make sure u have coin control enabled, allows u to select multiple inputs without mistakenly selecting the masternode's coins

" What is coin control? When you send bitcoins to someone else, the bitcoin client chooses kinda randomly which of your addresses will send the coins. With coin control you can exactly choose, which of your addresses will be the sending addresses. And even more specific which of your unspent outputs will be the sending inputs. - Geremia - bitcoin.stackexchange "

further assistance we advise onjoining our Discord Server where we have 24/7 superb tech customer service and a great helpful community  https://discord.gg/Aa3teGm

**Comment by aionmine-help** [comment]
Wow quick response.

This isnt about knowing how to use coin control.  That works perfectly.

Even with stake=0 in the lux.conf
When sending other inputs using coin control the wallet is unlocked from entering your password during the countdown from 5 to hit ok.

The 16120 can stake then.
Especially if you are slow to hit ok.

There are many examples of mn stakes in the blockchain including this.

https://chainz.cryptoid.info/lux/tx.dws?851563.htm
That is a masternode output staked not spent accidentally. 

Although this is a very minor issue.

Please take this seriously as many people could have an issue recreating their masternode output.

stake=0 is lux.conf is set the wallet can still stake during the time it is unlocked to when the user hits ok during the 5 second countdown. 

I am well aware that lux should be going through some amazing developments and this is miner issue.

Being able to stake with 
stake=0
In lux.conf
Is a minor bug not a criticism.

Thanks guys and keep up the awesome work!

**Comment by TopoX84** [comment]
on lux.conf 
stake=0 <-- wrong
**staking=0** <-- right way to stop staking

**Comment by aionmine-help** [comment]
@TopoX84 thanks for the response.
Works perfectly now, the document I referenced had the incorrect variable.

Obviously the issue here wasn't to do with luxcore so i'll close it!

I can't wait to see you next developments.  Thanks!
