### ISSUE TITLE
Integrate decentralized file storage with ipfs

### ISSUE THREAD

**Issue by IntegralTeam** [LUX-Core/lux#17]
Decentralized file storage (dfs) can be integrated with ipfs ipfs, but there are some difficulties:

- Dfs cannot use the storage format of a file that uses ipfs
- Dfs will not support the feature set used in ipfs
- Files stored in dfs will not be accessible from ipfs.

In this regard, the module of interaction between ipfs and dfs is required.

**Comment by giaki3003** [comment]
This has had 0 activity for a while now. Closing
