### ISSUE TITLE
v5.3.1 won't start: libboost_system.so.1.65.1: cannot open shared object file (Mint 18)

### ISSUE THREAD

**Issue by Shekelme** [LUX-Core/lux#25]
I can't start 5.3.1 wallet (lux-qt-linux-18) under Linux Mint 18:

`./lux-qt: error while loading shared libraries: libboost_system.so.1.65.1: cannot open shared object file: No such file or directory`

lux-qt-linux-16 is starting OK on the same system.

**Comment by TopoX84** [comment]
you might be missing dependencies
run the following code `sudo wget -L https://raw.githubusercontent.com/LUX-Core/lux/master/depends/install-dependencies.sh | sudo chmod +x install-dependencies.sh; sudo sh install-dependencies.sh`
you can find that script here https://github.com/LUX-Core/lux/blob/master/depends/install-dependencies.sh

i also would like to encourage you to join our discord where we have tech support around the clock https://discord.gg/d5fYZFW
