### ISSUE TITLE
scriptPubKey field in listunspent missing

### ISSUE THREAD

**Issue by unek** [LUX-Core/lux#26]
looks like it's been fixed in https://github.com/LUX-Core/lux/commit/7cb226b7a2bca23d076628e7ee12f3de3b578228 and then undone in https://github.com/LUX-Core/lux/commit/4035ff15eb5e3cc74729647df0d54f8976e6fe15

**Comment by giaki3003** [comment]
Fixed in 599e7fa80be9dd53bbffb59223615b62e1e0fc16 
Closing
