### ISSUE TITLE
QT wallet, stuck on black screen, built from source, Ubuntu 18.10 in VM 64 bit, x86 arch

### ISSUE THREAD

**Issue by Rowdster** [LUX-Core/lux#27]
Getting latest, QT wallet built from source is stuck on launch 

1. Dialog displays with 

![image](https://user-images.githubusercontent.com/575732/52990194-12532400-33d5-11e9-9547-a4c02bdb50a7.png)

On dismissal, app shows an empty black screen, with just the "luxcore" title bar.  

Ubuntu 18.10, Virtual Machine in Synology, 64 bit Intel CPU.  

No logs created in ~/.lux  

~/.lux/lux.conf is 0 bytes

**Comment by giaki3003** [comment]
Sounds like a depends issue. Had the same problem until i didn't update QT. Have you tried building using the depends system?

**Comment by Rowdster** [comment]
Building with the depends script build-linux.sh did the job.  Thanks.

**Comment by giaki3003** [comment]
Glad to know
Closing
