### ISSUE TITLE
immature amount less than 1 LUX included in balance

### ISSUE THREAD

**Issue by fastgrav** [LUX-Core/lux#3]
hi,

I compiled master and the issue opened on 216k's github is not fixed so I'm opening again:

./lux-cli getinfo
{
  "version": 5020000,
  "protocolversion": 69500,
  "walletversion": 61000,

./lux-cli listtransactions
look at amount ... it shows 0.0000  and it should be 0.2 lux reward
{
    "account": "",
    "address": "Lxxxxxxxxx",
    "category": "immature",
    "amount": 0.00000000,
    "label": "",
    "vout": 2,
    "confirmations": 19,
    "bcconfirmations": 19,
    "generated": true,

./lux-cli getbalance
16124.20000000 <-- here are included all 0.2 LUX with less than 80 confirmations

Andrei

**Comment by tpruvot** [comment]
yes, staking txs are not yet properly listed in listtransactions

try getwalletinfo for the balance details

**Comment by tpruvot** [comment]
If you (or someone else) have some other staking wallet with a proper listtransactions output, would be nice to have a reference/sample to keep the same format

**Comment by tpruvot** [comment]
Current testnet sample of a stake tx (noisy) => 2 - 0.4 (20%) => +1.6 in wallet

    {
      "account": "",
      "address": "LSUGht5WuwxprsESAiDq9onHQMpqvS5Mgb",
      "category": "generate",
      "amount": 2.00000000,
      "label": "",
      "vout": 1,
      "confirmations": 288,
      "bcconfirmations": 288,
      "generated": true,
      "blockhash": "9762f04f579b51a94f0bbd6618e288c1c8f9ac3cfebe6c4317b82c07eeafc626",
      "blockindex": 1,
      "blocktime": 1533122710,
      "txid": "fe395c0a3e93711197ea57182ee966fb426a366870fbd3329f0051bbd707cdfb",
      "walletconflicts": [
      ],
      "time": 1533122710,
      "timereceived": 1533122710
    }, 
    {
      "account": "",
      "address": "LfLYdQJhnPGQuRQbCwJuvZC76oL1Kv646Q",
      "category": "send",
      "amount": -0.40000000,
      "vout": 3,
      "confirmations": 288,
      "bcconfirmations": 288,
      "generated": true,
      "blockhash": "9762f04f579b51a94f0bbd6618e288c1c8f9ac3cfebe6c4317b82c07eeafc626",
      "blockindex": 1,
      "blocktime": 1533122710,
      "txid": "fe395c0a3e93711197ea57182ee966fb426a366870fbd3329f0051bbd707cdfb",
      "walletconflicts": [
      ],
      "time": 1533122710,
      "timereceived": 1533122710
    }, 
    {
      "account": "",
      "address": "LSUGht5WuwxprsESAiDq9onHQMpqvS5Mgb",
      "category": "send",
      "amount": -196.91000000,
      "label": "",
      "vout": 2,
      "confirmations": 288,
      "bcconfirmations": 288,
      "generated": true,
      "blockhash": "9762f04f579b51a94f0bbd6618e288c1c8f9ac3cfebe6c4317b82c07eeafc626",
      "blockindex": 1,
      "blocktime": 1533122710,
      "txid": "fe395c0a3e93711197ea57182ee966fb426a366870fbd3329f0051bbd707cdfb",
      "walletconflicts": [
      ],
      "time": 1533122710,
      "timereceived": 1533122710
    }, 
    {
      "account": "",
      "address": "LSUGht5WuwxprsESAiDq9onHQMpqvS5Mgb",
      "category": "send",
      "amount": -196.90000000,
      "label": "",
      "vout": 1,
      "confirmations": 288,
      "bcconfirmations": 288,
      "generated": true,
      "blockhash": "9762f04f579b51a94f0bbd6618e288c1c8f9ac3cfebe6c4317b82c07eeafc626",
      "blockindex": 1,
      "blocktime": 1533122710,
      "txid": "fe395c0a3e93711197ea57182ee966fb426a366870fbd3329f0051bbd707cdfb",
      "walletconflicts": [
      ],
      "time": 1533122710,
      "timereceived": 1533122710
    }, 
    {
      "account": "",
      "category": "send",
      "amount": 0.00000000,
      "vout": 0,
      "confirmations": 288,
      "bcconfirmations": 288,
      "generated": true,
      "blockhash": "9762f04f579b51a94f0bbd6618e288c1c8f9ac3cfebe6c4317b82c07eeafc626",
      "blockindex": 1,
      "blocktime": 1533122710,
      "txid": "fe395c0a3e93711197ea57182ee966fb426a366870fbd3329f0051bbd707cdfb",
      "walletconflicts": [
      ],
      "time": 1533122710,
      "timereceived": 1533122710
    }`

**Comment by tpruvot** [comment]
the last one is now ignored by commit 65ac1fa

**Comment by nguyenhoangtran11** [comment]
Could you please checkout bug_fix branch and test it?

**Comment by fastgrav** [comment]
compiling now

**Comment by fastgrav** [comment]
CXX      libbitcoin_server_a-rest.o
miner.cpp: In member function âvoid BlockAssembler::addPackageTxs(uint64_t)â:
miner.cpp:793:95: error: no match for call to â(CompareTxMemPoolEntryByAncestorFee) (const value_type&, CTxMemPoolModifiedEntry)â
                     CompareTxMemPoolEntryByAncestorFee()(*modit, CTxMemPoolModifiedEntry(iter))) { {
                                                                                               ^
In file included from miner.h:10:0,
                 from miner.cpp:6:
txmempool.h:297:10: note: candidate: bool CompareTxMemPoolEntryByAncestorFee::operator()(const CTxMemPoolEntry&, const CTxMemPoolEntry&) const
     bool operator()(const CTxMemPoolEntry& a, const CTxMemPoolEntry& b) const
          ^
txmempool.h:297:10: note:   no known conversion for argument 1 from âconst value_type {aka const CTxMemPoolModifiedEntry}â to âconst CTxMemPoolEntry&â
miner.cpp:799:15: error: expected â}â before âelseâ
             } else {
               ^
  CXX      libbitcoin_server_a-rpcblockchain.o
  CXX      libbitcoin_server_a-rpcdarksend.o
At global scope:
cc1plus: warning: unrecognized command line option â-Wno-implicit-fallthroughâ
Makefile:8532: recipe for target 'libbitcoin_server_a-miner.o' failed
make[2]: *** [libbitcoin_server_a-miner.o] Error 1
make[2]: *** Waiting for unfinished jobs....

make[2]: Leaving directory '/usr/src/lux/src'
Makefile:14590: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/usr/src/lux/src'
Makefile:608: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by tpruvot** [comment]
resolved

**Comment by fastgrav** [comment]
"immature_credit" branch solved the issue with balance and show the correct amount for:

 {
    "account": "",
    "address": "Lxxxxxxxxxxxxxx",
    "category": "immature",
    "amount": 0.20000000,
    "label": "",
    "vout": 2,
    "confirmations": 3,
    "bcconfirmations": 3,
    "generated": true,

Thank you
Andrei
