### ISSUE TITLE
balance inconsistency

### ISSUE THREAD

**Issue by fastgrav** [LUX-Core/lux#4]
Hi,

After importing priv key on a linux machine the balance value is different:

./lux-cli getinfo
"balance": 16128.80000000,  <--- balance  ok

 ./lux-cli listaddressgroupings
[
      "Lxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
      16129.00000000,  <--- it shows balance including immature transactions ... ok
      "mn1"
]

 ./lux-cli getbalance
16128.80000000  <--- balance ok

./lux-cli getbalance mn1
16226.40000000   <----- ???

I restarted luxd with -rescan option

I would like to import multiple addresses and acquire the balance for every address individually 
Any ideas ?

thanks,
Andrei

**Comment by tpruvot** [comment]
could you report "listaccounts" output ? and getwalletinfo one too ?

**Comment by fastgrav** [comment]
./lux-cli listaccounts
{
  "": -97.60000000,
  "mn1": 16226.60000000
}

 ./lux-cli getwalletinfo
{
  "walletversion": 61000,
  "balance": 16129.00000000,
  "unconfirmed_balance": 0.00000000,
  "immature_balance": 0.00000000,
  "txcount": 107,
  "keypoololdest": 1533291571,
  "keypoolsize": 199
}

**Comment by fastgrav** [comment]
started with an empty wallet and imported the priv key ... 
weird   "": -97.60000000,

**Comment by tpruvot** [comment]
try: move "mn1" "" 97.6

**Comment by fastgrav** [comment]
./lux-cli move "mn1" "" 97.6
true
 ./lux-cli getbalance mn1
16129.00000000
./lux-cli getbalance
16129.00000000

thank you Tanguy
Best regards,
Andrei

**Comment by tpruvot** [comment]
no problem, its a common behavior with imported accounts...
