### ISSUE TITLE
Make - Error 'Failing to include Boost library':

### ISSUE THREAD

**Issue by chitownmafia** [LUX-Core/lux#80]
uname -a:
    GE70-2OC-2OE 4.18.0-25-generic #26~18.04.1-Ubuntu SMP Thu Jun 27 07:28:31 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

    Error 'Failing to include Boost library':

make
Making all in src
make[1]: Entering directory '/home/philfrom1983/lux/src'
make[2]: Entering directory '/home/philfrom1983/lux/src'
make[3]: Entering directory '/home/philfrom1983/lux/src/secp256k1'
make[3]: Leaving directory '/home/philfrom1983/lux/src/secp256k1'
  CXXLD    luxd
libbitcoin_common.a(libbitcoin_common_a-ChainParams.o): In function `std::unordered_set<dev::FixedHash<20u>, std::hash<dev::FixedHash<20u> >, std::equal_to<dev::FixedHash<20u> >, std::allocator<dev::FixedHash<20u> > > dev::eth::commit<dev::MemoryDB>(std::unordered_map<dev::FixedHash<20u>, dev::eth::Account, std::hash<dev::FixedHash<20u> >, std::equal_to<dev::FixedHash<20u> >, std::allocator<std::pair<dev::FixedHash<20u> const, dev::eth::Account> > > const&, dev::SpecificTrieDB<dev::FatGenericTrieDB<dev::MemoryDB>, dev::FixedHash<20u> >&)':
/usr/include/boost/random/uniform_int_distribution.hpp:220: undefined reference to `boost::random::random_device::operator()()'
libbitcoin_common.a(libbitcoin_common_a-State.o): In function `unsigned long boost::random::detail::generate_uniform_int<boost::random::random_device, unsigned long>(boost::random::random_device&, unsigned long, unsigned long, mpl_::bool_<true>)':
/usr/include/boost/random/uniform_int_distribution.hpp:117: undefined reference to `boost::random::random_device::operator()()'
/usr/include/boost/random/uniform_int_distribution.hpp:220: undefined reference to `boost::random::random_device::operator()()'
/usr/include/boost/random/uniform_int_distribution.hpp:69: undefined reference to `boost::random::random_device::operator()()'
libbitcoin_common.a(libbitcoin_common_a-State.o): In function `dev::eth::CodeSizeCache::store(dev::FixedHash<32u> const&, unsigned long)':
/usr/include/boost/random/uniform_int_distribution.hpp:220: undefined reference to `boost::random::random_device::operator()()'
libbitcoin_common.a(libbitcoin_common_a-ICAP.o):/usr/include/boost/random/uniform_int_distribution.hpp:220: more undefined references to `boost::random::random_device::operator()()' follow
libbitcoin_common.a(libbitcoin_common_a-FixedHash.o): In function `__static_initialization_and_destruction_0':
/home/philfrom1983/lux/src/cpp-ethereum/libdevcore/FixedHash.cpp:29: undefined reference to `boost::random::random_device::random_device()'
/home/philfrom1983/lux/src/cpp-ethereum/libdevcore/FixedHash.cpp:29: undefined reference to `boost::random::random_device::~random_device()'
collect2: error: ld returned 1 exit status
Makefile:5350: recipe for target 'luxd' failed
make[2]: *** [luxd] Error 1
make[2]: Leaving directory '/home/philfrom1983/lux/src'
Makefile:16242: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/philfrom1983/lux/src'
Makefile:636: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

Fix:

./make LIBS+=-lboost_random

**Comment by chitownmafia** [comment]
I was following the Wiki by the way.. https://github.com/LUX-Core/lux/wiki/How-To-Build-Lux-Wallet-%3F

**Comment by giaki3003** [comment]
What's your boost version?

**Comment by giaki3003** [comment]
Closed for inactivity.
If you feel like this issue is still relevant, please open a new one.
Thanks.
