### ISSUE TITLE
fork lux coin

### ISSUE THREAD

**Issue by nxboost** [LUX-Core/lux#9]
hi, can we  with you to make a fork of your coin with your help ??

**Comment by nxboost** [comment]
we have a working coin, but we want to switch to your algorithm, we will not be competitors. we need a stable coin with masternodes,

**Comment by nguyenhoangtran11** [comment]
Please join our discord and contact us to discuss more about it

**Comment by dannyoooo** [comment]
Here is a link to join the discord server:  https://discord.gg/mU8HwNt

**Comment by tpruvot** [comment]
out of subject
